[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028780891150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/af4f548cdc7e37be3e5c5b8f4914d931/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000028780891480>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/af4f548cdc7e37be3e5c5b8f4914d931/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000287808917B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/af4f548cdc7e37be3e5c5b8f4914d931/element